import { Octokit } from "@octokit/rest";
import consola from "consola";
import type { PrResult } from "../modules/schemas";

export interface PushOptions {
  owner: string;
  repo: string;
  files: Array<{ path: string; content: string }>;
  title: string;
  body?: string;
  baseBranch?: string;
}

/**
 * GitHub API を使って PR を作成
 */
export async function createPullRequest(token: string, options: PushOptions): Promise<PrResult> {
  const octokit = new Octokit({ auth: token });
  const { owner, repo, files, title, body, baseBranch = "main" } = options;

  // 1. 認証ユーザー情報を取得
  const { data: user } = await octokit.users.getAuthenticated();
  const forkOwner = user.login;

  consola.info(`認証ユーザー: ${forkOwner}`);

  // 2. fork を確認・作成
  let forkRepo: string;
  try {
    const { data: fork } = await octokit.repos.get({
      owner: forkOwner,
      repo,
    });
    forkRepo = fork.name;
    consola.info(`既存の fork を使用: ${forkOwner}/${forkRepo}`);
  } catch {
    consola.info("fork を作成中...");
    const { data: fork } = await octokit.repos.createFork({
      owner,
      repo,
    });
    forkRepo = fork.name;
    consola.success(`fork を作成しました: ${forkOwner}/${forkRepo}`);

    // fork の同期を待つ
    await sleep(3000);
  }

  // 3. ベースブランチの最新コミット SHA を取得
  const { data: baseBranchRef } = await octokit.repos.getBranch({
    owner,
    repo,
    branch: baseBranch,
  });
  const baseSha = baseBranchRef.commit.sha;

  // 4. 新しいブランチ名を生成
  const branchName = `devenv-sync-${Date.now()}`;

  // 5. fork に新しいブランチを作成
  consola.info(`ブランチを作成中: ${branchName}`);
  await octokit.git.createRef({
    owner: forkOwner,
    repo: forkRepo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 6. ファイルを更新
  for (const file of files) {
    consola.info(`ファイルを更新中: ${file.path}`);

    // 既存ファイルの SHA を取得（存在する場合）
    let existingSha: string | undefined;
    try {
      const { data: existingFile } = await octokit.repos.getContent({
        owner: forkOwner,
        repo: forkRepo,
        path: file.path,
        ref: branchName,
      });
      if (!Array.isArray(existingFile) && existingFile.type === "file") {
        existingSha = existingFile.sha;
      }
    } catch {
      // ファイルが存在しない場合は新規作成
    }

    // ファイルを作成または更新
    await octokit.repos.createOrUpdateFileContents({
      owner: forkOwner,
      repo: forkRepo,
      path: file.path,
      message: `Update ${file.path}`,
      content: Buffer.from(file.content).toString("base64"),
      branch: branchName,
      sha: existingSha,
    });
  }

  // 7. PR を作成
  consola.info("PR を作成中...");
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body: body || generatePrBody(files),
    head: `${forkOwner}:${branchName}`,
    base: baseBranch,
  });

  consola.success(`PR を作成しました: ${pr.html_url}`);

  return {
    url: pr.html_url,
    number: pr.number,
    branch: branchName,
  };
}

/**
 * PR の本文を生成
 */
function generatePrBody(files: Array<{ path: string; content: string }>): string {
  const fileList = files.map((f) => `- \`${f.path}\``).join("\n");

  return `## 概要

create-devenv の push コマンドによる自動生成 PR です。

## 変更ファイル

${fileList}

---
Generated by [@tktco/create-devenv](https://github.com/tktcorporation/.github/tree/main/packages/create-devenv)
`;
}

/**
 * GitHub トークンを環境変数から取得
 */
export function getGitHubToken(): string | undefined {
  return process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
}

/**
 * sleep utility
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
